---
language: ruby
sudo: false
install: bundle install --without development
script: bundle exec rspec --color --format documentation
notifications:
  email: false
rvm:
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
